ems = [
    "Africa",
    "Asia",
    "Europe",
    "North America",
    "South America",
    "Ocienea",
    "World"
]

companies = [
    "apple",
    "microsoft",
    "walmart",
    "McDonalds",
    "tesla",
    "meta",
    "bilibili",
    "intel",
    "amazon",
    "nivida",
    "IBM",
    "shopify",
    "telus",
    "honda",
    "general motors",
    "toyota",
    "ford",
    "sony",
    "dell",
    "netflix",
    "alphabet",
    "spotify",
    "diney",
    "paramount",
    "door dash",
    "zoom",
    "black rock",
    "shell",
    "general electric",
    "phizer",
    "costco",
    "boeing",
    "target",
    "snap",
    "pintrest",
    "warner bros",
    "best buy",
    "cloudflare",
    "datadog",
    "crowdstrike",
    "snowflake",
    "gitlab",
    "zscaler",
    "fastly",
    "okta",
    "duolingo",
    "nike",
    "visa",
    "mastercard",
    "paypal",
    "saleforce",
    "american express",
    "adobe",
    "caterpillar",
    "service now",
    "workday",
    "autodesk",
    "atlassian",
    "hasbro",
    "mattel",
    "bp",
    "exxon mobile",
    "jhonsen and jhonsen",
    "chevron",
    "suncor",
    "amgen",
    "biogen",
    "regeneron pharmaceuticals",
    "vertex pharmaceuticals",
    "madrigal pharmaceuticals",
    "biomarin pharmaceuticals",
    "incyte",
    "exelixis",
    "new york times",
    ""
]

comps = [
    'XOM',
    'MSFT',
    'IBM',
    'NYT',
    'CRM',
    'V',
    'Now',
    'DDGOG',
    'SHOP',
    'UBER',
    'SNOW',
    'SQ',
    'PYPL',
    'ADBE',
    'MA',
    'AVGO',
    'PANW'
    'CRWD',
    'FTNT',
    'ORCL',
    'INTC',
    'CSCO',
    'DELL',
    'QCOM',
    'AMD',
    'MU',
    'TSM',
    'NVDA',
    'TSLA',
    'ARM',
    'META',
    'NFLX',
    'DIS',
    'PARA',
    'ROKU',
    'WBD',
    'GOOG',
    'AMC',
    'CO',
    'AMZN',
    'BA',
    'JPM',
    'LMT',
    'RTX',
    'NOC',
    'SPCE',
    'GE',
    'HLL',
    'HON',
    'LHX',
    '',
    '',
    '',
    '',
    '',
    '',
]

opts = [
    "emmisions",
    "companies value",
    "companies volume",
    "tempatures"
]

resources = [
    "oil",
    "gold",
    "copper",
    "silver",
    "platnium"
]

crypto = [
    "bitcoin",
    "dogecoin",
    "etherium",
    "tether",
    "solana"
]
